# Generated by Django 4.2.17 on 2024-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_platform_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webthreeuser',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webthreeuser',
            name='github',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webthreeuser',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webthreeuser',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webthreeuser',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
