version: "3.9"
services:
  freelancer_platform_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./db_backup:/var/lib/postgresql/data
